### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jacobweinstock**
There are many dependencies that have newer versions with fixes of all kinds, especially security related ones. This PR updates all dependencies to the latest.

### CODE REVIEW

**Comment by jacobweinstock** [comment]
Hey @tobert and @nshalman . Is this repo still being maintained?

**Review by nshalman — APPROVED** [review]
I don't know if I count as a maintainer, but we should certainly keep this repo maintained.

**Comment by tobert** [comment]
A few of us at Equinix have been bumping versions along on demand. It may
be worth looking at newer otel launchers that are likely more robust by
now. When we wrote it, it was among the first of its kind.

Thanks Nahum. Let's have a chat in January about responsible ongoing
maintenance of otel-init-go.

-Amy

**Comment by nshalman** [comment]
> newer otel launchers that are likely more robust by now

I didn't realize those existed. I'll have to look around at what's out there.

**Comment by nshalman** [comment]
Smee migrated off like so:
https://github.com/tinkerbell/smee/commit/b10ee0321942f041e7706aab10cc802585a24b48

**Pull request closed without merging**
